name: Build Android APK

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos de ejecución a gradlew
      run: chmod +x gradlew

    - name: Compilar APK de prueba
      run: ./gradlew assembleDebug

    - name: Subir archivo APK
      uses: actions/upload-artifact@v4
      with:
        name: mi-aplicacion-apk
        path: '**/build/outputs/apk/debug/*.apk'
